#!/usr/bin/env bash
# =============================================================================
# scripts/build.sh — the production artefact build
# =============================================================================
# This file used to be "auto-generated by @lark-apaas/fullstack-cli" and contained
# three steps that called 妙搭 platform tooling. All three are gone:
#
#   [0/6] `npx fullstack-cli action-plugin init`    — a platform CLI, not on the public
#         registry. It used to run `npx` against a same-named public package, which
#         printed an interactive prompt and aborted the build with exit 130 in any
#         non-TTY environment (CI, Docker). The step is meaningless here: it only
#         initialises `capabilities/`, and this repository has none.
#   [3/6] `generate-api-routes` / `generate-page-routes` — platform-internal tools that
#         do not exist on npm; they produced route-definition JSON consumed by the
#         platform's own route metadata, which nothing off-platform reads.
#   [5/6] the `polyfills.js` relocation — the platform preset injected a document.write
#         for `/assets/polyfills.js`, and because `/assets/` was on the platform's
#         skip-list the file had to be moved to the web root. Plain Vite emits no such
#         polyfill and no such injection; `client/index.html` is the whole story.
#
# What remains is the repository's own packaging logic, unchanged in behaviour:
#   * parallel server (SWC) + client (Vite) builds, with each failure reported;
#   * the built client published where the server actually reads it
#     (`dist/dist/client`, because the process runs with cwd = `dist/`);
#   * a hard check that every asset the entry HTML references really exists — the
#     guard for the white-screen class of bug that status-code-only tests cannot see;
#   * `run.sh` and `.env` staged next to the server entry point.
#
# IMPORTANT: `npm run build` uses SWC and does NOT typecheck. Run
# `npm run type:check:server` and `npm run type:check:client` as well.
# =============================================================================
set -euo pipefail

ROOT_DIR="$(pwd)"
DIST_DIR="$ROOT_DIR/dist"

# 记录总开始时间
TOTAL_START=$(node -e "console.log(Date.now())")

# 打印耗时的辅助函数
print_time() {
  local start=$1
  local end=$(node -e "console.log(Date.now())")
  local elapsed=$((end - start))
  local seconds=$((elapsed / 1000))
  local ms=$((elapsed % 1000))
  echo "   ⏱️  耗时: ${seconds}.$(printf "%03d" $ms)s"
}

# ==================== 步骤 1 ====================
echo "📝 [1/5] 更新 openapi 代码"
STEP_START=$(node -e "console.log(Date.now())")
npm run gen:openapi
print_time $STEP_START
echo ""

# ==================== 步骤 2 ====================
echo "🗑️  [2/5] 清理 dist 目录"
STEP_START=$(node -e "console.log(Date.now())")
rm -rf "$ROOT_DIR/dist"
print_time $STEP_START
echo ""

# ==================== 步骤 3 ====================
echo "🔨 [3/5] 并行构建 server 和 client"
STEP_START=$(node -e "console.log(Date.now())")

# 给 server/client 构建子进程预留 8GB heap，缓解 vite build transform 阶段 OOM
# （典型错误：Reached heap limit Allocation failed）。
# 仅在外部未设置 NODE_OPTIONS 时注入，允许 CI / 用户通过外部环境变量完全覆盖
BUILD_NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=2048}"

# 根据 only_frontend_change 决定是否构建 server
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "🔨 [3/5] 仅构建 client (only_frontend_change=true)"

  echo "   ├─ 启动 client 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:client > /tmp/build-client.log 2>&1
  CLIENT_EXIT=$?

  if [ $CLIENT_EXIT -ne 0 ]; then
    echo "   ❌ Client 构建失败"
    cat /tmp/build-client.log
    exit 1
  fi

  echo "   ✅ Client 构建完成"
else
  echo "🔨 [3/5] 并行构建 server 和 client"

  # 并行构建
  echo "   ├─ 启动 server 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:server > /tmp/build-server.log 2>&1 &
  SERVER_PID=$!

  echo "   ├─ 启动 client 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:client > /tmp/build-client.log 2>&1 &
  CLIENT_PID=$!

  # 等待两个构建完成
  SERVER_EXIT=0
  CLIENT_EXIT=0

  wait $SERVER_PID || SERVER_EXIT=$?
  wait $CLIENT_PID || CLIENT_EXIT=$?

  # 检查构建结果
  if [ $SERVER_EXIT -ne 0 ]; then
    echo "   ❌ Server 构建失败"
    cat /tmp/build-server.log
    exit 1
  fi

  if [ $CLIENT_EXIT -ne 0 ]; then
    echo "   ❌ Client 构建失败"
    cat /tmp/build-client.log
    exit 1
  fi

  echo "   ✅ Server 构建完成"
  echo "   ✅ Client 构建完成"
fi

print_time $STEP_START
echo ""

# ==================== 步骤 4 ====================
echo "📦 [4/5] 准备产物"
STEP_START=$(node -e "console.log(Date.now())")

# 为什么是 dist/dist/client
# ------------------------
# 服务进程以 cwd = dist/ 启动（Dockerfile 的 WORKDIR 与 `npm run start` 都是这样），
# 而 server/main.ts 把视图目录解析为 <cwd>/dist/client、静态目录也解析为同一个
# <cwd>/dist/client。所以真正的发布目录是 dist/dist/client —— 这里就是把它准备好。
if [ -d "$DIST_DIR/client" ]; then
  mkdir -p "$DIST_DIR/dist/client"
  # public 先进（顶层 client 打包被排除；server 的静态中间件与视图引擎同源 serve）
  if [ -d "$ROOT_DIR/client/public" ]; then
    cp -R "$ROOT_DIR/client/public/." "$DIST_DIR/dist/client/"
  fi

  # 构建产物 HTML 随后 move，覆盖 public 里的同名文件（保证入口页是构建版，
  # 不被 public 静默覆盖）。
  #
  # 任何深度的 HTML 都要搬：Vite 的输出目录是 dist/client，而入口文档在
  # client/index.html，所以它落在 dist/client/client/index.html（深度 2）。
  # 三层嵌套时把最内层的 index.html 提升为 dist/dist/client/index.html，
  # 视图引擎按固定名字查找它。
  (
    cd "$DIST_DIR/client" || exit 0
    find . -name "*.html" -print0 | while IFS= read -r -d '' html_file; do
      target_dir="$DIST_DIR/dist/client/$(dirname "$html_file")"
      mkdir -p "$target_dir"
      mv "$html_file" "$target_dir/"
    done
  )
  if [ ! -f "$DIST_DIR/dist/client/index.html" ]; then
    nested_index=$(find "$DIST_DIR/dist/client" -mindepth 2 -name "index.html" -print -quit 2>/dev/null || true)
    if [ -n "$nested_index" ]; then
      mv "$nested_index" "$DIST_DIR/dist/client/index.html"
    fi
  fi
  if [ ! -f "$DIST_DIR/dist/client/index.html" ]; then
    echo "   ❌ 构建失败：未找到入口 HTML，无法生成 dist/dist/client/index.html" >&2
    echo "      生产环境下 GET / 将无法渲染。请检查 vite.config.ts 的 rollupOptions.input。" >&2
    exit 1
  fi

  # 把静态资源也放进 dist/dist/client。
  # Vite 输出到 dist/client/bundle（assetsDir），而只有 HTML 会被上面那段搬走；
  # 不搬资源的话，浏览器请求 /bundle/xxx.js 会落到 SPA 回退，拿回一份 text/html
  # 的首页 —— 脚本永远加载不了，**页面白屏**，而健康检查、API、日志全部正常。
  # 复制而不是移动：保留 dist/client 的完整内容。
  for asset_dir in bundle assets static; do
    if [ -d "$DIST_DIR/client/$asset_dir" ]; then
      mkdir -p "$DIST_DIR/dist/client"
      cp -R "$DIST_DIR/client/$asset_dir" "$DIST_DIR/dist/client/"
    fi
  done

  # 验证：入口 HTML 引用的每一个本地资源都必须真实存在，否则直接构建失败。
  # 这道校验是必需的 —— 上面那个白屏缺陷整套测试都测不出来（所有套件只看
  # HTTP 状态码，而 SPA 回退让资源请求也返回 200）。
  if [ -f "$DIST_DIR/dist/client/index.html" ]; then
    missing=""
    for ref in $(grep -oE '(src|href)="/[^"]+"' "$DIST_DIR/dist/client/index.html" \
                 | sed -E 's/.*="\/([^"]+)"/\1/' | sort -u); do
      case "$ref" in
        *.js|*.css|*.svg|*.png|*.ico|*.webp|*.woff|*.woff2)
          if [ ! -f "$DIST_DIR/dist/client/$ref" ]; then
            missing="$missing $ref"
          fi
          ;;
      esac
    done
    if [ -n "$missing" ]; then
      echo "   ❌ 构建失败：入口 HTML 引用了不存在的静态资源，独立部署会白屏：" >&2
      for m in $missing; do echo "        /$m" >&2; done
      exit 1
    fi
    echo "   ✓ 入口 HTML 引用的静态资源均已就位于 dist/dist/client"
  fi
fi

# server 相关产物准备（only_frontend_change=true 时跳过）
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "   [skip] 跳过 run.sh/.env 复制 (only_frontend_change=true)"
else
  # 拷贝 run.sh 到 dist/（prod 从 dist/ 启动，确保 cwd 一致性）
  cp "$ROOT_DIR/scripts/run.sh" "$DIST_DIR/"

  # 拷贝 .env 文件（如果存在）
  if [ -f "$ROOT_DIR/.env" ]; then
    cp "$ROOT_DIR/.env" "$DIST_DIR/"
  fi
fi

# 清理无用文件
rm -rf "$DIST_DIR/scripts"
rm -rf "$DIST_DIR/tsconfig.node.tsbuildinfo"

print_time $STEP_START
echo ""

# ==================== 步骤 5 ====================
echo "✂️  [5/5] 智能依赖裁剪"
STEP_START=$(node -e "console.log(Date.now())")

# 智能依赖裁剪（仅全量构建时执行，纯前端场景不打包 server，无需裁剪）
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "✂️  [5/5] 跳过智能依赖裁剪 (only_frontend_change=true)"
else
  echo "✂️  [5/5] 智能依赖裁剪"

  # 分析实际依赖、复制并裁剪 node_modules、生成精简的 package.json
  # FIX (production hardening): scripts/prune-smart.js was referenced here but has never
  # existed in the repository. With `set -euo pipefail` at the top of this file, this line
  # made `npm run build` fail unconditionally at 步骤 [5/5]. Dependency pruning is an
  # ARTIFACT-SIZE OPTIMISATION, not a correctness requirement, so it is now skipped with a
  # loud notice when the tool is absent instead of failing the whole build.
  if [[ -f "$ROOT_DIR/scripts/prune-smart.js" ]]; then
    node "$ROOT_DIR/scripts/prune-smart.js"
  else
    echo "   ⚠️  跳过智能依赖裁剪：scripts/prune-smart.js 不存在"
    echo "      构建产物会包含完整 node_modules（体积更大，但功能不受影响）"
  fi
fi

print_time $STEP_START
echo ""

# 总耗时
echo "构建完成"
print_time $TOTAL_START

# 输出产物信息
DIST_SIZE=$(du -sh "$DIST_DIR" | cut -f1)
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo ""
  echo "📊 构建产物统计:"
  echo "   产物大小:        $DIST_SIZE"
  echo ""
else
  # FIX (production hardening): when scripts/prune-smart.js is absent, step [5/5] now
  # skips pruning, so $DIST_DIR/node_modules does not exist. The unguarded `du` below then
  # failed, and because this script runs under `set -euo pipefail` that aborted the build
  # with exit 1 EVEN THOUGH every build step had already succeeded.
  if [[ -d "$DIST_DIR/node_modules" ]]; then
    NODE_MODULES_SIZE=$(du -sh "$DIST_DIR/node_modules" | cut -f1)
  else
    NODE_MODULES_SIZE="(未裁剪，未复制到产物目录)"
  fi
  echo ""
  echo "📊 构建产物统计:"
  echo "   产物大小:        $DIST_SIZE"
  echo "   node_modules: $NODE_MODULES_SIZE"
  echo ""
fi
