#!/usr/bin/env bash
# This file is auto-generated by @lark-apaas/fullstack-cli
set -euo pipefail

ROOT_DIR="$(pwd)"
DIST_DIR="$ROOT_DIR/dist"

# 记录总开始时间
TOTAL_START=$(node -e "console.log(Date.now())")

# 打印耗时的辅助函数
print_time() {
  local start=$1
  local end=$(node -e "console.log(Date.now())")
  local elapsed=$((end - start))
  local seconds=$((elapsed / 1000))
  local ms=$((elapsed % 1000))
  echo "   ⏱️  耗时: ${seconds}.$(printf "%03d" $ms)s"
}

# ==================== 步骤 0 ====================
# FIX (production hardening): this step used to run `npx fullstack-cli action-plugin init`.
# `fullstack-cli` is not declared as a dependency and nothing in the tree provides that
# bin, so `npx` fetched an UNRELATED public package of the same name, which printed an
# interactive prompt ("What do you want to create? front / back / catalog") and aborted
# the build with exit 130 in any non-TTY environment (CI, Docker).
#
# The step is only meaningful when capabilities/ exists. It now runs solely against a
# locally resolvable binary (--no-install: never downloads a same-named stranger) and
# is skipped with a clear notice otherwise.
echo "🗑️  [0/6] 安装插件"
STEP_START=$(node -e "console.log(Date.now())")
if [[ ! -d "$ROOT_DIR/capabilities" ]]; then
  echo "   ⏭️  跳过：本项目没有 capabilities/ 目录，action-plugin 无需初始化"
elif npx --no-install fullstack-cli --version >/dev/null 2>&1; then
  npx --no-install fullstack-cli action-plugin init
else
  echo "   ⚠️  跳过：capabilities/ 存在但本地无法解析 fullstack-cli（不会联网下载同名第三方包）"
  echo "      如需该步骤，请先安装 lark-apaas 平台工具链；或设置 QLS_STRICT_PLATFORM_CLI=1 使其变为硬失败"
  if [[ "${QLS_STRICT_PLATFORM_CLI:-0}" == "1" ]]; then
    echo "   ❌ QLS_STRICT_PLATFORM_CLI=1：该步骤缺失视为致命错误" >&2
    exit 1
  fi
fi
print_time $STEP_START
echo ""

# ==================== 步骤 1 ====================
echo "📝 [1/6] 更新 openapi 代码"
STEP_START=$(node -e "console.log(Date.now())")
npm run gen:openapi
print_time $STEP_START
echo ""

# ==================== 步骤 2 ====================
echo "🗑️  [2/6] 清理 dist 目录"
STEP_START=$(node -e "console.log(Date.now())")
rm -rf "$ROOT_DIR/dist"
print_time $STEP_START
echo ""

# ==================== 步骤 3 ====================
echo "🗺️  [3/6] 生成路由定义"
STEP_START=$(node -e "console.log(Date.now())")

# 在 client/server 构建之前生成到 dist/，供 DefinePlugin 注入前端 bundle
# 注意：nest-cli.json 中 deleteOutDir 必须为 false（模板默认值），否则 nest build 会清掉 dist/
echo "   ├─ 生成 API 路由定义..."
npx generate-api-routes --server-dir ./server --out-dir ./dist > /tmp/gen-api-routes.log 2>&1 &
API_ROUTES_PID=$!

echo "   ├─ 生成页面路由定义..."
npx generate-page-routes --app-path ./client/src/app.tsx --out-dir ./dist > /tmp/gen-page-routes.log 2>&1 &
PAGE_ROUTES_PID=$!

API_ROUTES_EXIT=0
PAGE_ROUTES_EXIT=0

wait $API_ROUTES_PID || API_ROUTES_EXIT=$?
wait $PAGE_ROUTES_PID || PAGE_ROUTES_EXIT=$?

if [ $API_ROUTES_EXIT -ne 0 ]; then
  echo "   ⚠️  API 路由生成失败（不影响构建）"
  cat /tmp/gen-api-routes.log
else
  echo "   ✅ API 路由生成完成"
fi

if [ $PAGE_ROUTES_EXIT -ne 0 ]; then
  echo "   ⚠️  页面路由生成失败（不影响构建）"
  cat /tmp/gen-page-routes.log
else
  echo "   ✅ 页面路由生成完成"
fi
print_time $STEP_START
echo ""

# ==================== 步骤 4 ====================
echo "🔨 [4/6] 并行构建 server 和 client"
STEP_START=$(node -e "console.log(Date.now())")

# 给 server/client 构建子进程预留 8GB heap，缓解 vite build transform 阶段 OOM
# （典型错误：Reached heap limit Allocation failed）。
# 仅在外部未设置 NODE_OPTIONS 时注入，允许 CI / 用户通过外部环境变量完全覆盖
BUILD_NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=2048}"

# 根据 only_frontend_change 决定是否构建 server
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "🔨 [4/6] 仅构建 client (only_frontend_change=true)"

  echo "   ├─ 启动 client 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:client > /tmp/build-client.log 2>&1
  CLIENT_EXIT=$?

  if [ $CLIENT_EXIT -ne 0 ]; then
    echo "   ❌ Client 构建失败"
    cat /tmp/build-client.log
    exit 1
  fi

  echo "   ✅ Client 构建完成"
else
  echo "🔨 [4/6] 并行构建 server 和 client"

  # 并行构建
  echo "   ├─ 启动 server 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:server > /tmp/build-server.log 2>&1 &
  SERVER_PID=$!

  echo "   ├─ 启动 client 构建..."
  NODE_OPTIONS="$BUILD_NODE_OPTIONS" npm run build:client > /tmp/build-client.log 2>&1 &
  CLIENT_PID=$!

  # 等待两个构建完成
  SERVER_EXIT=0
  CLIENT_EXIT=0

  wait $SERVER_PID || SERVER_EXIT=$?
  wait $CLIENT_PID || CLIENT_EXIT=$?

  # 检查构建结果
  if [ $SERVER_EXIT -ne 0 ]; then
    echo "   ❌ Server 构建失败"
    cat /tmp/build-server.log
    exit 1
  fi

  if [ $CLIENT_EXIT -ne 0 ]; then
    echo "   ❌ Client 构建失败"
    cat /tmp/build-client.log
    exit 1
  fi

  echo "   ✅ Server 构建完成"
  echo "   ✅ Client 构建完成"
fi

print_time $STEP_START
echo ""

# ==================== 步骤 5 ====================
echo "📦 [5/6] 准备产物"
STEP_START=$(node -e "console.log(Date.now())")

# 移动 client 下的 HTML 文件到 dist/dist/client，保证 views 路径在 dev/prod 下一致
# 使用 mv 而非 cp：HTML 不能上传到公网 CDN，移走后 dist/client 中不再包含 HTML
if [ -d "$DIST_DIR/client" ]; then
  mkdir -p "$DIST_DIR/dist/client"
  # public 先进（顶层 client 打包被排除；server setBaseViewsDir + 中间件同源 serve）
  if [ -d "$ROOT_DIR/client/public" ]; then
    cp -R "$ROOT_DIR/client/public/." "$DIST_DIR/dist/client/"
  fi
  # 构建产物 HTML 随后 move，覆盖 public 里的同名文件（保证入口页是构建版，不被 public 静默覆盖）
  #
  # FIX (production hardening): this used to be a `-maxdepth 1` search:
  #     find "$DIST_DIR/client" -maxdepth 1 -name "*.html" -exec mv {} ... \;
  # The current Vite preset emits the entry document at
  #     dist/client/client/index.html          (depth 2, NOT depth 1)
  # so the glob matched nothing and the HTML was never moved. The production server sets
  # its view directory to <cwd>/dist/client and is started with cwd=dist (see run.sh),
  # i.e. dist/dist/client — which therefore had no index.html, and `GET /` could not
  # render the app. Verified: before this fix dist/dist/client contained only favicon.svg.
  #
  # Now every emitted HTML is moved at any depth (preserving relative paths), and a nested
  # entry document is promoted to dist/dist/client/index.html so the view engine finds it.
  (
    cd "$DIST_DIR/client" || exit 0
    find . -name "*.html" -print0 | while IFS= read -r -d '' html_file; do
      target_dir="$DIST_DIR/dist/client/$(dirname "$html_file")"
      mkdir -p "$target_dir"
      mv "$html_file" "$target_dir/"
    done
  )
  if [ ! -f "$DIST_DIR/dist/client/index.html" ]; then
    nested_index=$(find "$DIST_DIR/dist/client" -mindepth 2 -name "index.html" -print -quit 2>/dev/null || true)
    if [ -n "$nested_index" ]; then
      mv "$nested_index" "$DIST_DIR/dist/client/index.html"
    fi
  fi
  if [ ! -f "$DIST_DIR/dist/client/index.html" ]; then
    echo "   ❌ 构建失败：未找到入口 HTML，无法生成 dist/dist/client/index.html" >&2
    echo "      生产环境下 GET / 将无法渲染。请检查 Vite 预设的输出目录配置。" >&2
    exit 1
  fi

  # ---------------------------------------------------------------------------
  # 把静态资源也放进 dist/dist/client —— 独立部署必需
  # ---------------------------------------------------------------------------
  # 平台的 publicAssetsMiddleware()（@lark-apaas/fullstack-nestjs-core:36674）
  # 从 `path.resolve(process.cwd(), "dist/client")` 直出文件，而服务是以 cwd=dist
  # 启动的，所以它的实际目录是 **dist/dist/client**。
  #
  # 但 Vite 把资源输出到 dist/client，上面这段只把 HTML 搬进了 dist/dist/client。
  # 在妙搭平台上，整个 dist/client 会被上传到 CDN，`/assets/*` 由 CDN 提供，所以
  # 一直正常；**独立部署时没有任何人上传它**，于是：
  #   请求 /assets|/bundle/xxx.js -> 中间件在 dist/dist/client 里找不到 -> next()
  #   -> SPA 回退 -> 返回 text/html 的首页 -> 浏览器把 HTML 当脚本 -> 页面白屏。
  # 而健康检查、API、日志全部正常，所以这个故障极难自查。
  #
  # 这里把非 HTML 的静态资源也复制过去，使中间件能在自己的目录里找到它们。
  # 复制而不是移动：保留 dist/client 的完整内容，妙搭的 CDN 上传流程不受影响。
  #
  # 注意 `assets/` 同时出现在平台中间件的 PLATFORM_PREFIXES 跳过列表里
  # （其注释写明 hashed 产物走 CDN），所以 vite 的 assetsDir 已改为 `bundle`
  # （见 vite.config.ts）。这里仍把 assets/ 一并复制，以兼容其它静态文件。
  for asset_dir in bundle assets static; do
    if [ -d "$DIST_DIR/client/$asset_dir" ]; then
      mkdir -p "$DIST_DIR/dist/client"
      cp -R "$DIST_DIR/client/$asset_dir" "$DIST_DIR/dist/client/"
    fi
  done

  # 验证：入口 HTML 引用的每一个本地资源都必须真实存在，否则直接构建失败。
  # 这道校验是必需的 —— 上面那个白屏缺陷整套测试都测不出来（所有套件只看
  # HTTP 状态码，而 SPA 回退让资源请求也返回 200）。
  if [ -f "$DIST_DIR/dist/client/index.html" ]; then
    missing=""
    for ref in $(grep -oE '(src|href)="/[^"]+"' "$DIST_DIR/dist/client/index.html" \
                 | sed -E 's/.*="\/([^"]+)"/\1/' | sort -u); do
      case "$ref" in
        *.js|*.css|*.svg|*.png|*.ico|*.webp|*.woff|*.woff2)
          if [ ! -f "$DIST_DIR/dist/client/$ref" ]; then
            missing="$missing $ref"
          fi
          ;;
      esac
    done
    if [ -n "$missing" ]; then
      echo "   ❌ 构建失败：入口 HTML 引用了不存在的静态资源，独立部署会白屏：" >&2
      for m in $missing; do echo "        /$m" >&2; done
      exit 1
    fi
    # polyfills.js 由预设输出到 assets/，而 assets/ 在平台中间件的跳过列表里
    # （走 CDN），独立部署时同样拿不到。挪到根目录并改写引用。
    if [ -f "$DIST_DIR/dist/client/assets/polyfills.js" ] && \
       [ ! -f "$DIST_DIR/dist/client/polyfills.js" ]; then
      cp "$DIST_DIR/dist/client/assets/polyfills.js" "$DIST_DIR/dist/client/polyfills.js"
      sed -i.bak 's#/assets/polyfills\.js#/polyfills.js#g' "$DIST_DIR/dist/client/index.html" \
        && rm -f "$DIST_DIR/dist/client/index.html.bak"
      echo "   ✓ polyfills.js 已从被平台跳过的 assets/ 移到根目录"
    fi
    echo "   ✓ 入口 HTML 引用的静态资源均已就位于 dist/dist/client"
  fi
fi

# server 相关产物准备（only_frontend_change=true 时跳过）
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "   [skip] 跳过 run.sh/.env 复制 (only_frontend_change=true)"
else
  # 拷贝 run.sh 到 dist/（prod 从 dist/ 启动，确保 cwd 一致性）
  cp "$ROOT_DIR/scripts/run.sh" "$DIST_DIR/"

  # 拷贝 .env 文件（如果存在）
  if [ -f "$ROOT_DIR/.env" ]; then
    cp "$ROOT_DIR/.env" "$DIST_DIR/"
  fi
fi

# 清理无用文件
rm -rf "$DIST_DIR/scripts"
rm -rf "$DIST_DIR/tsconfig.node.tsbuildinfo"

print_time $STEP_START
echo ""

# ==================== 步骤 6 ====================
echo "✂️  [6/6] 智能依赖裁剪"
STEP_START=$(node -e "console.log(Date.now())")

# 智能依赖裁剪（仅全量构建时执行，纯前端场景不打包 server，无需裁剪）
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo "✂️  [6/6] 跳过智能依赖裁剪 (only_frontend_change=true)"
else
  echo "✂️  [6/6] 智能依赖裁剪"

  # 分析实际依赖、复制并裁剪 node_modules、生成精简的 package.json
  # FIX (production hardening): scripts/prune-smart.js was referenced here but has never
  # existed in the repository. With `set -euo pipefail` at the top of this file, this line
  # made `npm run build` fail unconditionally at step [6/6]. Dependency pruning is an
  # ARTIFACT-SIZE OPTIMISATION, not a correctness requirement, so it is now skipped with a
  # loud notice when the tool is absent instead of failing the whole build.
  if [[ -f "$ROOT_DIR/scripts/prune-smart.js" ]]; then
    node "$ROOT_DIR/scripts/prune-smart.js"
  else
    echo "   ⚠️  跳过智能依赖裁剪：scripts/prune-smart.js 不存在"
    echo "      构建产物会包含完整 node_modules（体积更大，但功能不受影响）"
  fi
fi

print_time $STEP_START
echo ""

# 总耗时
echo "构建完成"
print_time $TOTAL_START

# 输出产物信息
DIST_SIZE=$(du -sh "$DIST_DIR" | cut -f1)
if [[ "${only_frontend_change:-false}" == "true" ]]; then
  echo ""
  echo "📊 构建产物统计:"
  echo "   产物大小:        $DIST_SIZE"
  echo ""
else
  # FIX (production hardening): when scripts/prune-smart.js is absent, step [6/6] now
  # skips pruning, so $DIST_DIR/node_modules does not exist. The unguarded `du` below then
  # failed, and because this script runs under `set -euo pipefail` that aborted the build
  # with exit 1 EVEN THOUGH every build step had already succeeded.
  if [[ -d "$DIST_DIR/node_modules" ]]; then
    NODE_MODULES_SIZE=$(du -sh "$DIST_DIR/node_modules" | cut -f1)
  else
    NODE_MODULES_SIZE="(未裁剪，未复制到产物目录)"
  fi
  echo ""
  echo "📊 构建产物统计:"
  echo "   产物大小:        $DIST_SIZE"
  echo "   node_modules: $NODE_MODULES_SIZE"
  echo ""
fi
