#!/usr/bin/env bash
# =============================================================================
# scripts/run.sh — start the production server
# =============================================================================
# This file used to carry an "auto-generated by <platform CLI>" header. Nothing
# generates it any more; what it does is one thing, and both parts of it matter:
#
#   * cwd = dist/ — the server resolves the built client and the cover-asset tree
#     relative to `process.cwd()` (server/main.ts), so starting from anywhere else
#     would answer 200 to /api/health and 404 to every asset and cover.
#   * NODE_ENV=production — cookie `Secure` flags, sanitised error bodies and
#     `abortOnError` all key off it.
# =============================================================================

# 生产环境下，启动服务
# 从 dist/ 根目录执行，确保 process.cwd() 与 dev 模式一致
# dev: cwd = 项目根, shared/ client/ 可达
# prod: cwd = dist/,  shared/ client/ 可达
NODE_ENV=production node server/main.js
